# Generated by Django 5.0.3 on 2024-03-20 17:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='service_type',
            fields=[
                ('code_type', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('type_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('service_id', models.IntegerField(primary_key=True, serialize=False)),
                ('service_desc', models.CharField(max_length=150)),
                ('service_location', models.URLField()),
                ('service_date', models.DateField()),
                ('deleted', models.BooleanField(default=False)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Services.service_type')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_desc', models.CharField(max_length=120)),
                ('report_date_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Services.service')),
            ],
        ),
        migrations.CreateModel(
            name='RateFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('feedback_content', models.CharField(max_length=120)),
                ('feedback_date', models.DateField()),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Services.service')),
            ],
        ),
        migrations.CreateModel(
            name='service_photos',
            fields=[
                ('photo_id', models.AutoField(primary_key=True, serialize=False)),
                ('url_link', models.URLField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Services.service')),
            ],
        ),
    ]
