# Generated by Django 5.0.3 on 2024-03-20 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_Services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='areas',
            fields=[
                ('code_area', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('area_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='service_location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='_Services.areas'),
        ),
    ]
