# Generated by Django 5.0.3 on 2024-03-23 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_Services', '0002_areas_alter_service_service_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_title',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
