# Generated by Django 5.0.3 on 2024-03-23 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('_Services', '0003_service_service_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='service_photos',
        ),
    ]
